//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for ExpansionProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpansionProfile">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DomainResource">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://hl7.org/fhir}uri" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" minOccurs="0"/>
 *         &lt;element name="version" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://hl7.org/fhir}code"/>
 *         &lt;element name="experimental" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="publisher" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="contact" type="{http://hl7.org/fhir}ExpansionProfile.Contact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="date" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="description" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="codeSystem" type="{http://hl7.org/fhir}ExpansionProfile.CodeSystem" minOccurs="0"/>
 *         &lt;element name="includeDesignations" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="designation" type="{http://hl7.org/fhir}ExpansionProfile.Designation" minOccurs="0"/>
 *         &lt;element name="includeDefinition" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="includeInactive" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="excludeNested" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="excludeNotForUI" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="excludePostCoordinated" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *         &lt;element name="displayLanguage" type="{http://hl7.org/fhir}code" minOccurs="0"/>
 *         &lt;element name="limitedExpansion" type="{http://hl7.org/fhir}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpansionProfile", propOrder = {
    "url",
    "identifier",
    "version",
    "name",
    "status",
    "experimental",
    "publisher",
    "contact",
    "date",
    "description",
    "codeSystem",
    "includeDesignations",
    "designation",
    "includeDefinition",
    "includeInactive",
    "excludeNested",
    "excludeNotForUI",
    "excludePostCoordinated",
    "displayLanguage",
    "limitedExpansion"
})
@javax.xml.bind.annotation.XmlRootElement(name="ExpansionProfile") 
public class ExpansionProfile
    extends DomainResource
{

    protected Uri url;
    protected Identifier identifier;
    protected String version;
    protected String name;
    @XmlElement(required = true)
    protected Code status;
    protected Boolean experimental;
    protected String publisher;
    protected List<ExpansionProfileContact> contact;
    protected DateTime date;
    protected String description;
    protected ExpansionProfileCodeSystem codeSystem;
    protected Boolean includeDesignations;
    protected ExpansionProfileDesignation designation;
    protected Boolean includeDefinition;
    protected Boolean includeInactive;
    protected Boolean excludeNested;
    protected Boolean excludeNotForUI;
    protected Boolean excludePostCoordinated;
    protected Code displayLanguage;
    protected Boolean limitedExpansion;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link Uri }
     *     
     */
    public Uri getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uri }
     *     
     */
    public void setUrl(Uri value) {
        this.url = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setStatus(Code value) {
        this.status = value;
    }

    /**
     * Gets the value of the experimental property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getExperimental() {
        return experimental;
    }

    /**
     * Sets the value of the experimental property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExperimental(Boolean value) {
        this.experimental = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpansionProfileContact }
     * 
     * 
     */
    public List<ExpansionProfileContact> getContact() {
        if (contact == null) {
            contact = new ArrayList<ExpansionProfileContact>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setDate(DateTime value) {
        this.date = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the codeSystem property.
     * 
     * @return
     *     possible object is
     *     {@link ExpansionProfileCodeSystem }
     *     
     */
    public ExpansionProfileCodeSystem getCodeSystem() {
        return codeSystem;
    }

    /**
     * Sets the value of the codeSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpansionProfileCodeSystem }
     *     
     */
    public void setCodeSystem(ExpansionProfileCodeSystem value) {
        this.codeSystem = value;
    }

    /**
     * Gets the value of the includeDesignations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIncludeDesignations() {
        return includeDesignations;
    }

    /**
     * Sets the value of the includeDesignations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeDesignations(Boolean value) {
        this.includeDesignations = value;
    }

    /**
     * Gets the value of the designation property.
     * 
     * @return
     *     possible object is
     *     {@link ExpansionProfileDesignation }
     *     
     */
    public ExpansionProfileDesignation getDesignation() {
        return designation;
    }

    /**
     * Sets the value of the designation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpansionProfileDesignation }
     *     
     */
    public void setDesignation(ExpansionProfileDesignation value) {
        this.designation = value;
    }

    /**
     * Gets the value of the includeDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIncludeDefinition() {
        return includeDefinition;
    }

    /**
     * Sets the value of the includeDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeDefinition(Boolean value) {
        this.includeDefinition = value;
    }

    /**
     * Gets the value of the includeInactive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIncludeInactive() {
        return includeInactive;
    }

    /**
     * Sets the value of the includeInactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeInactive(Boolean value) {
        this.includeInactive = value;
    }

    /**
     * Gets the value of the excludeNested property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getExcludeNested() {
        return excludeNested;
    }

    /**
     * Sets the value of the excludeNested property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludeNested(Boolean value) {
        this.excludeNested = value;
    }

    /**
     * Gets the value of the excludeNotForUI property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getExcludeNotForUI() {
        return excludeNotForUI;
    }

    /**
     * Sets the value of the excludeNotForUI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludeNotForUI(Boolean value) {
        this.excludeNotForUI = value;
    }

    /**
     * Gets the value of the excludePostCoordinated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getExcludePostCoordinated() {
        return excludePostCoordinated;
    }

    /**
     * Sets the value of the excludePostCoordinated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludePostCoordinated(Boolean value) {
        this.excludePostCoordinated = value;
    }

    /**
     * Gets the value of the displayLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getDisplayLanguage() {
        return displayLanguage;
    }

    /**
     * Sets the value of the displayLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setDisplayLanguage(Code value) {
        this.displayLanguage = value;
    }

    /**
     * Gets the value of the limitedExpansion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getLimitedExpansion() {
        return limitedExpansion;
    }

    /**
     * Sets the value of the limitedExpansion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLimitedExpansion(Boolean value) {
        this.limitedExpansion = value;
    }

}
