/*
 * Copyright (c) 2006-2007 Massachusetts General Hospital 
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the i2b2 Software License v1.0 
 * which accompanies this distribution. 
 * 
 * Contributors:
 * 		Kavishwar Wagholikar (kavi)
 * 		July 4, 2015
 */

/*
 * Copyright (c) 2006-2007 Massachusetts General Hospital 
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the i2b2 Software License v1.0 
 * which accompanies this distribution. 
 * 
 * Contributors:
 * 		Kavishwar Wagholikar (kavi)
 * 		July 4, 2015
 */

/*
 * Copyright (c) 2006-2007 Massachusetts General Hospital 
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the i2b2 Software License v1.0 
 * which accompanies this distribution. 
 * 
 * Contributors:
 * 		Kavishwar Wagholikar (kavi)
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 02:29:55 PM EDT 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for at least one of the defined elements, an @id referenced from the Narrative, or extensions
 * 
 * <p>Java class for BackboneElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackboneElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}Element">
 *       &lt;sequence>
 *         &lt;element name="modifierExtension" type="{http://hl7.org/fhir}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackboneElement", propOrder = {
    "modifierExtension"
})
@XmlSeeAlso({
    ContractSigner.class,
    ProvenanceEntity.class,
    DocumentReferenceRelatesTo.class,
    ImagingObjectSelectionFrames.class,
    ContractRule.class,
    ConformanceMessaging.class,
    EncounterStatusHistory.class,
    ClaimResponseError.class,
    ClaimResponseDetail.class,
    ProcessRequestItem.class,
    SubstanceIngredient.class,
    ValueSetParameter.class,
    PractitionerPractitionerRole.class,
    ImmunizationRecommendationDateCriterion.class,
    DocumentManifestContent.class,
    ObservationRelated.class,
    CompositionSection.class,
    MedicationPackage.class,
    ValueSetContact.class,
    NutritionOrderSupplement.class,
    SpecimenContainer.class,
    CompositionAttester.class,
    ValueSetContains.class,
    NamingSystemUniqueId.class,
    ImagingObjectSelectionSeries.class,
    PatientCommunication.class,
    ClaimResponseDetail1 .class,
    MedicationStatementDosage.class,
    ImagingObjectSelectionInstance.class,
    DocumentReferenceContext.class,
    AuditEventSource.class,
    ProcedureDevice.class,
    MessageHeaderDestination.class,
    ClaimMissingTeeth.class,
    ImmunizationExplanation.class,
    ContractValuedItem.class,
    ClaimResponseAdjudication.class,
    MedicationAdministrationDosage.class,
    QuestionnaireAnswersAnswer.class,
    SupplyDispense.class,
    ConformanceImplementation.class,
    StructureDefinitionMapping.class,
    ValueSetFilter.class,
    DeviceComponentProductionSpecification.class,
    ImagingStudySeries.class,
    ConditionDueTo.class,
    HealthcareServiceNotAvailable.class,
    HealthcareServiceServiceType.class,
    CarePlanActivity.class,
    SpecimenTreatment.class,
    CommunicationRequestPayload.class,
    ClaimResponseAddItem.class,
    ContractActor.class,
    ContraindicationMitigation.class,
    ConditionEvidence.class,
    QuestionnaireQuestion.class,
    ClaimSubDetail.class,
    AuditEventEvent.class,
    OperationDefinitionContact.class,
    OperationOutcomeIssue.class,
    NutritionOrderNutrient.class,
    MedicationContent.class,
    ContractLegal.class,
    ConditionStage.class,
    ConformanceDocument.class,
    MedicationPrescriptionDosageInstruction.class,
    ClaimCoverage.class,
    ContractValuedItem1 .class,
    ConformanceContact.class,
    ProcedureRelatedItem.class,
    HealthcareServiceAvailableTime.class,
    BundleTransactionResponse.class,
    ContractTerm.class,
    ClaimDiagnosis.class,
    ConformanceSecurity.class,
    MedicationDispenseSubstitution.class,
    StructureDefinitionDifferential.class,
    ConceptMapContact.class,
    DocumentReferenceRelated.class,
    NutritionOrderTexture.class,
    ConformanceResource.class,
    PersonLink.class,
    DocumentManifestRelated.class,
    ContractActor1 .class,
    ImagingStudyInstance.class,
    ImmunizationVaccinationProtocol.class,
    QuestionnaireGroup.class,
    CarePlanDetail.class,
    CommunicationPayload.class,
    ConceptMapDependsOn.class,
    CompositionEvent.class,
    PatientContact.class,
    ValueSetCompose.class,
    ListEntry.class,
    ConformanceInteraction1 .class,
    ConditionOccurredFollowing.class,
    ConformanceSearchParam.class,
    ConformanceSoftware.class,
    AuditEventNetwork.class,
    AuditEventDetail.class,
    DiagnosticReportImage.class,
    ClaimResponseSubDetail.class,
    ClaimResponseCoverage.class,
    EncounterParticipant.class,
    DeviceMetricCalibration.class,
    ProcedurePerformer.class,
    RiskAssessmentPrediction.class,
    ProcedureRequestBodySite.class,
    ClaimItem.class,
    NutritionOrderEnteralFormula.class,
    SpecimenCollection.class,
    ProvenanceAgent.class,
    CarePlanParticipant.class,
    NamingSystemContact.class,
    ConformanceCertificate.class,
    DiagnosticOrderEvent.class,
    ConformanceRest.class,
    MedicationPrescriptionDispense.class,
    ValueSetConcept.class,
    ConformanceOperation.class,
    MedicationPrescriptionSubstitution.class,
    ClaimResponseAdjudication1 .class,
    ProcedureBodySite.class,
    ClaimResponseAdjudication2 .class,
    DataElementMapping.class,
    ClaimResponseAdjudication3 .class,
    ClaimResponseAdjudication4 .class,
    BundleTransaction.class,
    SearchParameterContact.class,
    GoalOutcome.class,
    OrganizationContact.class,
    ObservationReferenceRange.class,
    QuestionnaireAnswersGroup.class,
    MedicationProduct.class,
    ImmunizationRecommendationProtocol.class,
    StructureDefinitionContact.class,
    OperationDefinitionParameter.class,
    GroupCharacteristic.class,
    ConceptMapMap.class,
    AuditEventObject.class,
    SubstanceInstance.class,
    DataElementContact.class,
    StructureDefinitionSnapshot.class,
    BundleEntry.class,
    ClinicalImpressionFinding.class,
    ConditionLocation.class,
    BundleSearch.class,
    AppointmentParticipant.class,
    MedicationIngredient.class,
    PractitionerQualification.class,
    OperationDefinitionPart.class,
    ImmunizationReaction.class,
    SubscriptionChannel.class,
    AuditEventParticipant.class,
    AllergyIntoleranceEvent.class,
    ConceptMapElement.class,
    OrderWhen.class,
    ContractFriendly.class,
    EncounterLocation.class,
    MedicationBatch.class,
    EpisodeOfCareCareTeam.class,
    FamilyMemberHistoryCondition.class,
    QuestionnaireAnswersQuestion.class,
    DiagnosticOrderItem.class,
    MedicationDispenseDosageInstruction.class,
    ClaimResponseItem.class,
    ConformanceInteraction.class,
    EncounterHospitalization.class,
    PatientLink.class,
    ImagingObjectSelectionStudy.class,
    ValueSetDefine.class,
    NutritionOrderOralDiet.class,
    ClaimDetail.class,
    ClaimProsthesis.class,
    PatientAnimal.class,
    ClinicalImpressionInvestigations.class,
    LocationPosition.class,
    ConformanceEvent.class,
    ClinicalImpressionRuledOut.class,
    PaymentReconciliationNote.class,
    ValueSetConcept1 .class,
    EpisodeOfCareStatusHistory.class,
    PaymentReconciliationDetail.class,
    VisionPrescriptionDispense.class,
    ValueSetInclude.class,
    ClaimResponseNote.class,
    MessageHeaderSource.class,
    MessageHeaderResponse.class,
    ValueSetExpansion.class,
    BundleLink.class,
    ClaimPayee.class,
    ImmunizationRecommendationRecommendation.class,
    ProcessResponseNotes.class,
    ValueSetDesignation.class
})
public class BackboneElement
    extends Element
{

    protected List<Extension> modifierExtension;

    /**
     * Gets the value of the modifierExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modifierExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifierExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * 
     * 
     */
    public List<Extension> getModifierExtension() {
        if (modifierExtension == null) {
            modifierExtension = new ArrayList<Extension>();
        }
        return this.modifierExtension;
    }

}
