//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for Claim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Claim">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DomainResource">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://hl7.org/fhir}ClaimType"/>
 *         &lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ruleset" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="originalRuleset" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="created" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="billablePeriod" type="{http://hl7.org/fhir}Period" minOccurs="0"/>
 *         &lt;element name="target" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="provider" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="organization" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="use" type="{http://hl7.org/fhir}Use" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="fundsReserve" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="enterer" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="facility" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="relatedClaim" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="prescription" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="originalPrescription" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="payee" type="{http://hl7.org/fhir}Claim.Payee" minOccurs="0"/>
 *         &lt;element name="referral" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="diagnosis" type="{http://hl7.org/fhir}Claim.Diagnosis" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specialCondition" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patient" type="{http://hl7.org/fhir}Reference"/>
 *         &lt;element name="coverage" type="{http://hl7.org/fhir}Claim.Coverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="exception" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="school" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="accidentDate" type="{http://hl7.org/fhir}date" minOccurs="0"/>
 *         &lt;element name="accidentType" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="accidentLocationString" type="{http://hl7.org/fhir}string"/>
 *           &lt;element name="accidentLocationAddress" type="{http://hl7.org/fhir}Address"/>
 *           &lt;element name="accidentLocationReference" type="{http://hl7.org/fhir}Reference"/>
 *         &lt;/choice>
 *         &lt;element name="interventionException" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="onsetDate" type="{http://hl7.org/fhir}date"/>
 *           &lt;element name="onsetPeriod" type="{http://hl7.org/fhir}Period"/>
 *         &lt;/choice>
 *         &lt;element name="employmentImpacted" type="{http://hl7.org/fhir}Period" minOccurs="0"/>
 *         &lt;element name="hospitalization" type="{http://hl7.org/fhir}Period" minOccurs="0"/>
 *         &lt;element name="item" type="{http://hl7.org/fhir}Claim.Item" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="total" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="additionalMaterials" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="missingTeeth" type="{http://hl7.org/fhir}Claim.MissingTeeth" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Claim", propOrder = {
    "type",
    "identifier",
    "ruleset",
    "originalRuleset",
    "created",
    "billablePeriod",
    "target",
    "provider",
    "organization",
    "use",
    "priority",
    "fundsReserve",
    "enterer",
    "facility",
    "relatedClaim",
    "prescription",
    "originalPrescription",
    "payee",
    "referral",
    "diagnosis",
    "specialCondition",
    "patient",
    "coverage",
    "exception",
    "school",
    "accidentDate",
    "accidentType",
    "accidentLocationString",
    "accidentLocationAddress",
    "accidentLocationReference",
    "interventionException",
    "onsetDate",
    "onsetPeriod",
    "employmentImpacted",
    "hospitalization",
    "item",
    "total",
    "additionalMaterials",
    "missingTeeth"
})
@javax.xml.bind.annotation.XmlRootElement(name="Claim") 
public class Claim
    extends DomainResource
{

    @XmlElement(required = true)
    protected ClaimType type;
    protected List<Identifier> identifier;
    protected Coding ruleset;
    protected Coding originalRuleset;
    protected DateTime created;
    protected Period billablePeriod;
    protected Reference target;
    protected Reference provider;
    protected Reference organization;
    protected Use use;
    protected Coding priority;
    protected Coding fundsReserve;
    protected Reference enterer;
    protected Reference facility;
    protected List<Reference> relatedClaim;
    protected Reference prescription;
    protected Reference originalPrescription;
    protected ClaimPayee payee;
    protected Reference referral;
    protected List<ClaimDiagnosis> diagnosis;
    protected List<Coding> specialCondition;
    @XmlElement(required = true)
    protected Reference patient;
    protected List<ClaimCoverage> coverage;
    protected List<Coding> exception;
    protected String school;
    protected Date accidentDate;
    protected Coding accidentType;
    protected String accidentLocationString;
    protected Address accidentLocationAddress;
    protected Reference accidentLocationReference;
    protected List<Coding> interventionException;
    protected Date onsetDate;
    protected Period onsetPeriod;
    protected Period employmentImpacted;
    protected Period hospitalization;
    protected List<ClaimItem> item;
    protected Money total;
    protected List<Coding> additionalMaterials;
    protected List<ClaimMissingTeeth> missingTeeth;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimType }
     *     
     */
    public ClaimType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimType }
     *     
     */
    public void setType(ClaimType value) {
        this.type = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the ruleset property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getRuleset() {
        return ruleset;
    }

    /**
     * Sets the value of the ruleset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setRuleset(Coding value) {
        this.ruleset = value;
    }

    /**
     * Gets the value of the originalRuleset property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getOriginalRuleset() {
        return originalRuleset;
    }

    /**
     * Sets the value of the originalRuleset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setOriginalRuleset(Coding value) {
        this.originalRuleset = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setCreated(DateTime value) {
        this.created = value;
    }

    /**
     * Gets the value of the billablePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getBillablePeriod() {
        return billablePeriod;
    }

    /**
     * Sets the value of the billablePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setBillablePeriod(Period value) {
        this.billablePeriod = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setTarget(Reference value) {
        this.target = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setProvider(Reference value) {
        this.provider = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setOrganization(Reference value) {
        this.organization = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link Use }
     *     
     */
    public Use getUse() {
        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link Use }
     *     
     */
    public void setUse(Use value) {
        this.use = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setPriority(Coding value) {
        this.priority = value;
    }

    /**
     * Gets the value of the fundsReserve property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getFundsReserve() {
        return fundsReserve;
    }

    /**
     * Sets the value of the fundsReserve property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setFundsReserve(Coding value) {
        this.fundsReserve = value;
    }

    /**
     * Gets the value of the enterer property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getEnterer() {
        return enterer;
    }

    /**
     * Sets the value of the enterer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setEnterer(Reference value) {
        this.enterer = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setFacility(Reference value) {
        this.facility = value;
    }

    /**
     * Gets the value of the relatedClaim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedClaim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedClaim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getRelatedClaim() {
        if (relatedClaim == null) {
            relatedClaim = new ArrayList<Reference>();
        }
        return this.relatedClaim;
    }

    /**
     * Gets the value of the prescription property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getPrescription() {
        return prescription;
    }

    /**
     * Sets the value of the prescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setPrescription(Reference value) {
        this.prescription = value;
    }

    /**
     * Gets the value of the originalPrescription property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getOriginalPrescription() {
        return originalPrescription;
    }

    /**
     * Sets the value of the originalPrescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setOriginalPrescription(Reference value) {
        this.originalPrescription = value;
    }

    /**
     * Gets the value of the payee property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimPayee }
     *     
     */
    public ClaimPayee getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimPayee }
     *     
     */
    public void setPayee(ClaimPayee value) {
        this.payee = value;
    }

    /**
     * Gets the value of the referral property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReferral() {
        return referral;
    }

    /**
     * Sets the value of the referral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReferral(Reference value) {
        this.referral = value;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClaimDiagnosis }
     * 
     * 
     */
    public List<ClaimDiagnosis> getDiagnosis() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<ClaimDiagnosis>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the specialCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getSpecialCondition() {
        if (specialCondition == null) {
            specialCondition = new ArrayList<Coding>();
        }
        return this.specialCondition;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setPatient(Reference value) {
        this.patient = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClaimCoverage }
     * 
     * 
     */
    public List<ClaimCoverage> getCoverage() {
        if (coverage == null) {
            coverage = new ArrayList<ClaimCoverage>();
        }
        return this.coverage;
    }

    /**
     * Gets the value of the exception property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exception property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getException() {
        if (exception == null) {
            exception = new ArrayList<Coding>();
        }
        return this.exception;
    }

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchool() {
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchool(String value) {
        this.school = value;
    }

    /**
     * Gets the value of the accidentDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getAccidentDate() {
        return accidentDate;
    }

    /**
     * Sets the value of the accidentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setAccidentDate(Date value) {
        this.accidentDate = value;
    }

    /**
     * Gets the value of the accidentType property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getAccidentType() {
        return accidentType;
    }

    /**
     * Sets the value of the accidentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setAccidentType(Coding value) {
        this.accidentType = value;
    }

    /**
     * Gets the value of the accidentLocationString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentLocationString() {
        return accidentLocationString;
    }

    /**
     * Sets the value of the accidentLocationString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentLocationString(String value) {
        this.accidentLocationString = value;
    }

    /**
     * Gets the value of the accidentLocationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAccidentLocationAddress() {
        return accidentLocationAddress;
    }

    /**
     * Sets the value of the accidentLocationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAccidentLocationAddress(Address value) {
        this.accidentLocationAddress = value;
    }

    /**
     * Gets the value of the accidentLocationReference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAccidentLocationReference() {
        return accidentLocationReference;
    }

    /**
     * Sets the value of the accidentLocationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAccidentLocationReference(Reference value) {
        this.accidentLocationReference = value;
    }

    /**
     * Gets the value of the interventionException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interventionException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterventionException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getInterventionException() {
        if (interventionException == null) {
            interventionException = new ArrayList<Coding>();
        }
        return this.interventionException;
    }

    /**
     * Gets the value of the onsetDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getOnsetDate() {
        return onsetDate;
    }

    /**
     * Sets the value of the onsetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setOnsetDate(Date value) {
        this.onsetDate = value;
    }

    /**
     * Gets the value of the onsetPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getOnsetPeriod() {
        return onsetPeriod;
    }

    /**
     * Sets the value of the onsetPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setOnsetPeriod(Period value) {
        this.onsetPeriod = value;
    }

    /**
     * Gets the value of the employmentImpacted property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getEmploymentImpacted() {
        return employmentImpacted;
    }

    /**
     * Sets the value of the employmentImpacted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setEmploymentImpacted(Period value) {
        this.employmentImpacted = value;
    }

    /**
     * Gets the value of the hospitalization property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getHospitalization() {
        return hospitalization;
    }

    /**
     * Sets the value of the hospitalization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setHospitalization(Period value) {
        this.hospitalization = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClaimItem }
     * 
     * 
     */
    public List<ClaimItem> getItem() {
        if (item == null) {
            item = new ArrayList<ClaimItem>();
        }
        return this.item;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setTotal(Money value) {
        this.total = value;
    }

    /**
     * Gets the value of the additionalMaterials property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalMaterials property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalMaterials().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getAdditionalMaterials() {
        if (additionalMaterials == null) {
            additionalMaterials = new ArrayList<Coding>();
        }
        return this.additionalMaterials;
    }

    /**
     * Gets the value of the missingTeeth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the missingTeeth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMissingTeeth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClaimMissingTeeth }
     * 
     * 
     */
    public List<ClaimMissingTeeth> getMissingTeeth() {
        if (missingTeeth == null) {
            missingTeeth = new ArrayList<ClaimMissingTeeth>();
        }
        return this.missingTeeth;
    }

}
