//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for ExplanationOfBenefit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExplanationOfBenefit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DomainResource">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="claim" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="claimResponse" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="ruleset" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="originalRuleset" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="created" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="billablePeriod" type="{http://hl7.org/fhir}Period" minOccurs="0"/>
 *         &lt;element name="disposition" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="provider" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="organization" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="facility" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="relatedClaim" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="prescription" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="originalPrescription" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="payee" type="{http://hl7.org/fhir}ExplanationOfBenefit.Payee" minOccurs="0"/>
 *         &lt;element name="referral" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *         &lt;element name="diagnosis" type="{http://hl7.org/fhir}ExplanationOfBenefit.Diagnosis" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specialCondition" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patient" type="{http://hl7.org/fhir}Reference"/>
 *         &lt;element name="precedence" type="{http://hl7.org/fhir}positiveInt" minOccurs="0"/>
 *         &lt;element name="coverage" type="{http://hl7.org/fhir}ExplanationOfBenefit.Coverage"/>
 *         &lt;element name="exception" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="school" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="accidentDate" type="{http://hl7.org/fhir}date" minOccurs="0"/>
 *         &lt;element name="accidentType" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="accidentLocationString" type="{http://hl7.org/fhir}string"/>
 *           &lt;element name="accidentLocationAddress" type="{http://hl7.org/fhir}Address"/>
 *           &lt;element name="accidentLocationReference" type="{http://hl7.org/fhir}Reference"/>
 *         &lt;/choice>
 *         &lt;element name="interventionException" type="{http://hl7.org/fhir}Coding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="onsetDate" type="{http://hl7.org/fhir}date"/>
 *           &lt;element name="onsetPeriod" type="{http://hl7.org/fhir}Period"/>
 *         &lt;/choice>
 *         &lt;element name="employmentImpacted" type="{http://hl7.org/fhir}Period" minOccurs="0"/>
 *         &lt;element name="hospitalization" type="{http://hl7.org/fhir}Period" minOccurs="0"/>
 *         &lt;element name="item" type="{http://hl7.org/fhir}ExplanationOfBenefit.Item" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="addItem" type="{http://hl7.org/fhir}ExplanationOfBenefit.AddItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="claimTotal" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="missingTeeth" type="{http://hl7.org/fhir}ExplanationOfBenefit.MissingTeeth" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="unallocDeductable" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="totalBenefit" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="paymentAdjustment" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="paymentAdjustmentReason" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="paymentDate" type="{http://hl7.org/fhir}date" minOccurs="0"/>
 *         &lt;element name="paymentAmount" type="{http://hl7.org/fhir}Money" minOccurs="0"/>
 *         &lt;element name="paymentRef" type="{http://hl7.org/fhir}Identifier" minOccurs="0"/>
 *         &lt;element name="reserved" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="form" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="note" type="{http://hl7.org/fhir}ExplanationOfBenefit.Note" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="benefitBalance" type="{http://hl7.org/fhir}ExplanationOfBenefit.BenefitBalance" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExplanationOfBenefit", propOrder = {
    "identifier",
    "claim",
    "claimResponse",
    "ruleset",
    "originalRuleset",
    "created",
    "billablePeriod",
    "disposition",
    "provider",
    "organization",
    "facility",
    "relatedClaim",
    "prescription",
    "originalPrescription",
    "payee",
    "referral",
    "diagnosis",
    "specialCondition",
    "patient",
    "precedence",
    "coverage",
    "exception",
    "school",
    "accidentDate",
    "accidentType",
    "accidentLocationString",
    "accidentLocationAddress",
    "accidentLocationReference",
    "interventionException",
    "onsetDate",
    "onsetPeriod",
    "employmentImpacted",
    "hospitalization",
    "item",
    "addItem",
    "claimTotal",
    "missingTeeth",
    "unallocDeductable",
    "totalBenefit",
    "paymentAdjustment",
    "paymentAdjustmentReason",
    "paymentDate",
    "paymentAmount",
    "paymentRef",
    "reserved",
    "form",
    "note",
    "benefitBalance"
})
@javax.xml.bind.annotation.XmlRootElement(name="ExplanationOfBenefit") 
public class ExplanationOfBenefit
    extends DomainResource
{

    protected List<Identifier> identifier;
    protected Reference claim;
    protected Reference claimResponse;
    protected Coding ruleset;
    protected Coding originalRuleset;
    protected DateTime created;
    protected Period billablePeriod;
    protected String disposition;
    protected Reference provider;
    protected Reference organization;
    protected Reference facility;
    protected List<Reference> relatedClaim;
    protected Reference prescription;
    protected Reference originalPrescription;
    protected ExplanationOfBenefitPayee payee;
    protected Reference referral;
    protected List<ExplanationOfBenefitDiagnosis> diagnosis;
    protected List<Coding> specialCondition;
    @XmlElement(required = true)
    protected Reference patient;
    protected PositiveInt precedence;
    @XmlElement(required = true)
    protected ExplanationOfBenefitCoverage coverage;
    protected List<Coding> exception;
    protected String school;
    protected Date accidentDate;
    protected Coding accidentType;
    protected String accidentLocationString;
    protected Address accidentLocationAddress;
    protected Reference accidentLocationReference;
    protected List<Coding> interventionException;
    protected Date onsetDate;
    protected Period onsetPeriod;
    protected Period employmentImpacted;
    protected Period hospitalization;
    protected List<ExplanationOfBenefitItem> item;
    protected List<ExplanationOfBenefitAddItem> addItem;
    protected Money claimTotal;
    protected List<ExplanationOfBenefitMissingTeeth> missingTeeth;
    protected Money unallocDeductable;
    protected Money totalBenefit;
    protected Money paymentAdjustment;
    protected Coding paymentAdjustmentReason;
    protected Date paymentDate;
    protected Money paymentAmount;
    protected Identifier paymentRef;
    protected Coding reserved;
    protected Coding form;
    protected List<ExplanationOfBenefitNote> note;
    protected List<ExplanationOfBenefitBenefitBalance> benefitBalance;

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the claim property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getClaim() {
        return claim;
    }

    /**
     * Sets the value of the claim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setClaim(Reference value) {
        this.claim = value;
    }

    /**
     * Gets the value of the claimResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getClaimResponse() {
        return claimResponse;
    }

    /**
     * Sets the value of the claimResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setClaimResponse(Reference value) {
        this.claimResponse = value;
    }

    /**
     * Gets the value of the ruleset property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getRuleset() {
        return ruleset;
    }

    /**
     * Sets the value of the ruleset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setRuleset(Coding value) {
        this.ruleset = value;
    }

    /**
     * Gets the value of the originalRuleset property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getOriginalRuleset() {
        return originalRuleset;
    }

    /**
     * Sets the value of the originalRuleset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setOriginalRuleset(Coding value) {
        this.originalRuleset = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setCreated(DateTime value) {
        this.created = value;
    }

    /**
     * Gets the value of the billablePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getBillablePeriod() {
        return billablePeriod;
    }

    /**
     * Sets the value of the billablePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setBillablePeriod(Period value) {
        this.billablePeriod = value;
    }

    /**
     * Gets the value of the disposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisposition() {
        return disposition;
    }

    /**
     * Sets the value of the disposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisposition(String value) {
        this.disposition = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setProvider(Reference value) {
        this.provider = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setOrganization(Reference value) {
        this.organization = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setFacility(Reference value) {
        this.facility = value;
    }

    /**
     * Gets the value of the relatedClaim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedClaim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedClaim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getRelatedClaim() {
        if (relatedClaim == null) {
            relatedClaim = new ArrayList<Reference>();
        }
        return this.relatedClaim;
    }

    /**
     * Gets the value of the prescription property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getPrescription() {
        return prescription;
    }

    /**
     * Sets the value of the prescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setPrescription(Reference value) {
        this.prescription = value;
    }

    /**
     * Gets the value of the originalPrescription property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getOriginalPrescription() {
        return originalPrescription;
    }

    /**
     * Sets the value of the originalPrescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setOriginalPrescription(Reference value) {
        this.originalPrescription = value;
    }

    /**
     * Gets the value of the payee property.
     * 
     * @return
     *     possible object is
     *     {@link ExplanationOfBenefitPayee }
     *     
     */
    public ExplanationOfBenefitPayee getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplanationOfBenefitPayee }
     *     
     */
    public void setPayee(ExplanationOfBenefitPayee value) {
        this.payee = value;
    }

    /**
     * Gets the value of the referral property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReferral() {
        return referral;
    }

    /**
     * Sets the value of the referral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReferral(Reference value) {
        this.referral = value;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplanationOfBenefitDiagnosis }
     * 
     * 
     */
    public List<ExplanationOfBenefitDiagnosis> getDiagnosis() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<ExplanationOfBenefitDiagnosis>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the specialCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getSpecialCondition() {
        if (specialCondition == null) {
            specialCondition = new ArrayList<Coding>();
        }
        return this.specialCondition;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setPatient(Reference value) {
        this.patient = value;
    }

    /**
     * Gets the value of the precedence property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveInt }
     *     
     */
    public PositiveInt getPrecedence() {
        return precedence;
    }

    /**
     * Sets the value of the precedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveInt }
     *     
     */
    public void setPrecedence(PositiveInt value) {
        this.precedence = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link ExplanationOfBenefitCoverage }
     *     
     */
    public ExplanationOfBenefitCoverage getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplanationOfBenefitCoverage }
     *     
     */
    public void setCoverage(ExplanationOfBenefitCoverage value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the exception property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exception property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getException() {
        if (exception == null) {
            exception = new ArrayList<Coding>();
        }
        return this.exception;
    }

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchool() {
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchool(String value) {
        this.school = value;
    }

    /**
     * Gets the value of the accidentDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getAccidentDate() {
        return accidentDate;
    }

    /**
     * Sets the value of the accidentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setAccidentDate(Date value) {
        this.accidentDate = value;
    }

    /**
     * Gets the value of the accidentType property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getAccidentType() {
        return accidentType;
    }

    /**
     * Sets the value of the accidentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setAccidentType(Coding value) {
        this.accidentType = value;
    }

    /**
     * Gets the value of the accidentLocationString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccidentLocationString() {
        return accidentLocationString;
    }

    /**
     * Sets the value of the accidentLocationString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccidentLocationString(String value) {
        this.accidentLocationString = value;
    }

    /**
     * Gets the value of the accidentLocationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAccidentLocationAddress() {
        return accidentLocationAddress;
    }

    /**
     * Sets the value of the accidentLocationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAccidentLocationAddress(Address value) {
        this.accidentLocationAddress = value;
    }

    /**
     * Gets the value of the accidentLocationReference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAccidentLocationReference() {
        return accidentLocationReference;
    }

    /**
     * Sets the value of the accidentLocationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAccidentLocationReference(Reference value) {
        this.accidentLocationReference = value;
    }

    /**
     * Gets the value of the interventionException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interventionException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterventionException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coding }
     * 
     * 
     */
    public List<Coding> getInterventionException() {
        if (interventionException == null) {
            interventionException = new ArrayList<Coding>();
        }
        return this.interventionException;
    }

    /**
     * Gets the value of the onsetDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getOnsetDate() {
        return onsetDate;
    }

    /**
     * Sets the value of the onsetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setOnsetDate(Date value) {
        this.onsetDate = value;
    }

    /**
     * Gets the value of the onsetPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getOnsetPeriod() {
        return onsetPeriod;
    }

    /**
     * Sets the value of the onsetPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setOnsetPeriod(Period value) {
        this.onsetPeriod = value;
    }

    /**
     * Gets the value of the employmentImpacted property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getEmploymentImpacted() {
        return employmentImpacted;
    }

    /**
     * Sets the value of the employmentImpacted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setEmploymentImpacted(Period value) {
        this.employmentImpacted = value;
    }

    /**
     * Gets the value of the hospitalization property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getHospitalization() {
        return hospitalization;
    }

    /**
     * Sets the value of the hospitalization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setHospitalization(Period value) {
        this.hospitalization = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplanationOfBenefitItem }
     * 
     * 
     */
    public List<ExplanationOfBenefitItem> getItem() {
        if (item == null) {
            item = new ArrayList<ExplanationOfBenefitItem>();
        }
        return this.item;
    }

    /**
     * Gets the value of the addItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplanationOfBenefitAddItem }
     * 
     * 
     */
    public List<ExplanationOfBenefitAddItem> getAddItem() {
        if (addItem == null) {
            addItem = new ArrayList<ExplanationOfBenefitAddItem>();
        }
        return this.addItem;
    }

    /**
     * Gets the value of the claimTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getClaimTotal() {
        return claimTotal;
    }

    /**
     * Sets the value of the claimTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setClaimTotal(Money value) {
        this.claimTotal = value;
    }

    /**
     * Gets the value of the missingTeeth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the missingTeeth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMissingTeeth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplanationOfBenefitMissingTeeth }
     * 
     * 
     */
    public List<ExplanationOfBenefitMissingTeeth> getMissingTeeth() {
        if (missingTeeth == null) {
            missingTeeth = new ArrayList<ExplanationOfBenefitMissingTeeth>();
        }
        return this.missingTeeth;
    }

    /**
     * Gets the value of the unallocDeductable property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getUnallocDeductable() {
        return unallocDeductable;
    }

    /**
     * Sets the value of the unallocDeductable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setUnallocDeductable(Money value) {
        this.unallocDeductable = value;
    }

    /**
     * Gets the value of the totalBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getTotalBenefit() {
        return totalBenefit;
    }

    /**
     * Sets the value of the totalBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setTotalBenefit(Money value) {
        this.totalBenefit = value;
    }

    /**
     * Gets the value of the paymentAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getPaymentAdjustment() {
        return paymentAdjustment;
    }

    /**
     * Sets the value of the paymentAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setPaymentAdjustment(Money value) {
        this.paymentAdjustment = value;
    }

    /**
     * Gets the value of the paymentAdjustmentReason property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getPaymentAdjustmentReason() {
        return paymentAdjustmentReason;
    }

    /**
     * Sets the value of the paymentAdjustmentReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setPaymentAdjustmentReason(Coding value) {
        this.paymentAdjustmentReason = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setPaymentDate(Date value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setPaymentAmount(Money value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the paymentRef property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getPaymentRef() {
        return paymentRef;
    }

    /**
     * Sets the value of the paymentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setPaymentRef(Identifier value) {
        this.paymentRef = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setReserved(Coding value) {
        this.reserved = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setForm(Coding value) {
        this.form = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplanationOfBenefitNote }
     * 
     * 
     */
    public List<ExplanationOfBenefitNote> getNote() {
        if (note == null) {
            note = new ArrayList<ExplanationOfBenefitNote>();
        }
        return this.note;
    }

    /**
     * Gets the value of the benefitBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the benefitBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBenefitBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplanationOfBenefitBenefitBalance }
     * 
     * 
     */
    public List<ExplanationOfBenefitBenefitBalance> getBenefitBalance() {
        if (benefitBalance == null) {
            benefitBalance = new ArrayList<ExplanationOfBenefitBenefitBalance>();
        }
        return this.benefitBalance;
    }

}
