//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurePopulationType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasurePopulationType-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="initial-population"/>
 *     &lt;enumeration value="numerator"/>
 *     &lt;enumeration value="numerator-exclusion"/>
 *     &lt;enumeration value="denominator"/>
 *     &lt;enumeration value="denominator-exclusion"/>
 *     &lt;enumeration value="denominator-exception"/>
 *     &lt;enumeration value="measure-population"/>
 *     &lt;enumeration value="measure-population-exclusion"/>
 *     &lt;enumeration value="measure-score"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MeasurePopulationType-list")
@XmlEnum
public enum MeasurePopulationTypeList {


    /**
     * The initial population for the measure
     * 
     */
    @XmlEnumValue("initial-population")
    INITIAL_POPULATION("initial-population"),

    /**
     * The numerator for the measure
     * 
     */
    @XmlEnumValue("numerator")
    NUMERATOR("numerator"),

    /**
     * The numerator exclusion for the measure
     * 
     */
    @XmlEnumValue("numerator-exclusion")
    NUMERATOR_EXCLUSION("numerator-exclusion"),

    /**
     * The denominator for the measure
     * 
     */
    @XmlEnumValue("denominator")
    DENOMINATOR("denominator"),

    /**
     * The denominator exclusion for the measure
     * 
     */
    @XmlEnumValue("denominator-exclusion")
    DENOMINATOR_EXCLUSION("denominator-exclusion"),

    /**
     * The denominator exception for the measure
     * 
     */
    @XmlEnumValue("denominator-exception")
    DENOMINATOR_EXCEPTION("denominator-exception"),

    /**
     * The measure population for the measure
     * 
     */
    @XmlEnumValue("measure-population")
    MEASURE_POPULATION("measure-population"),

    /**
     * The measure population exclusion for the measure
     * 
     */
    @XmlEnumValue("measure-population-exclusion")
    MEASURE_POPULATION_EXCLUSION("measure-population-exclusion"),

    /**
     * The measure score for the measure
     * 
     */
    @XmlEnumValue("measure-score")
    MEASURE_SCORE("measure-score");
    private final java.lang.String value;

    MeasurePopulationTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static MeasurePopulationTypeList fromValue(java.lang.String v) {
        for (MeasurePopulationTypeList c: MeasurePopulationTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
