/*
 * Copyright (c) 2006-2007 Massachusetts General Hospital 
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the i2b2 Software License v1.0 
 * which accompanies this distribution. 
 * 
 * Contributors:
 * 		Kavishwar Wagholikar (kavi)
 * 		July 4, 2015
 */

/*
 * Copyright (c) 2006-2007 Massachusetts General Hospital 
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the i2b2 Software License v1.0 
 * which accompanies this distribution. 
 * 
 * Contributors:
 * 		Kavishwar Wagholikar (kavi)
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 02:29:55 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to a patient/resident.
 * 
 * <p>Java class for NutritionOrder.EnteralFormula complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NutritionOrder.EnteralFormula">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="administrationInstructions" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="baseFormulaType" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="baseFormulaProductName" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="scheduled" type="{http://hl7.org/fhir}Timing" minOccurs="0"/>
 *         &lt;element name="additiveType" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="additiveProductName" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="caloricDensity" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="routeofAdministration" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="quantity" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="rate" type="{http://hl7.org/fhir}Ratio" minOccurs="0"/>
 *         &lt;element name="rateAdjustment" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *         &lt;element name="maxVolumeToDeliver" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NutritionOrder.EnteralFormula", propOrder = {
    "administrationInstructions",
    "baseFormulaType",
    "baseFormulaProductName",
    "scheduled",
    "additiveType",
    "additiveProductName",
    "caloricDensity",
    "routeofAdministration",
    "quantity",
    "rate",
    "rateAdjustment",
    "maxVolumeToDeliver"
})
public class NutritionOrderEnteralFormula
    extends BackboneElement
{

    protected String administrationInstructions;
    protected CodeableConcept baseFormulaType;
    protected String baseFormulaProductName;
    protected Timing scheduled;
    protected CodeableConcept additiveType;
    protected String additiveProductName;
    protected Quantity caloricDensity;
    protected CodeableConcept routeofAdministration;
    protected Quantity quantity;
    protected Ratio rate;
    protected Quantity rateAdjustment;
    protected Quantity maxVolumeToDeliver;

    /**
     * Gets the value of the administrationInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministrationInstructions() {
        return administrationInstructions;
    }

    /**
     * Sets the value of the administrationInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministrationInstructions(String value) {
        this.administrationInstructions = value;
    }

    /**
     * Gets the value of the baseFormulaType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getBaseFormulaType() {
        return baseFormulaType;
    }

    /**
     * Sets the value of the baseFormulaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setBaseFormulaType(CodeableConcept value) {
        this.baseFormulaType = value;
    }

    /**
     * Gets the value of the baseFormulaProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseFormulaProductName() {
        return baseFormulaProductName;
    }

    /**
     * Sets the value of the baseFormulaProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseFormulaProductName(String value) {
        this.baseFormulaProductName = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     * @return
     *     possible object is
     *     {@link Timing }
     *     
     */
    public Timing getScheduled() {
        return scheduled;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timing }
     *     
     */
    public void setScheduled(Timing value) {
        this.scheduled = value;
    }

    /**
     * Gets the value of the additiveType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getAdditiveType() {
        return additiveType;
    }

    /**
     * Sets the value of the additiveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setAdditiveType(CodeableConcept value) {
        this.additiveType = value;
    }

    /**
     * Gets the value of the additiveProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditiveProductName() {
        return additiveProductName;
    }

    /**
     * Sets the value of the additiveProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditiveProductName(String value) {
        this.additiveProductName = value;
    }

    /**
     * Gets the value of the caloricDensity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getCaloricDensity() {
        return caloricDensity;
    }

    /**
     * Sets the value of the caloricDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setCaloricDensity(Quantity value) {
        this.caloricDensity = value;
    }

    /**
     * Gets the value of the routeofAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getRouteofAdministration() {
        return routeofAdministration;
    }

    /**
     * Sets the value of the routeofAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setRouteofAdministration(CodeableConcept value) {
        this.routeofAdministration = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setQuantity(Quantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link Ratio }
     *     
     */
    public Ratio getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ratio }
     *     
     */
    public void setRate(Ratio value) {
        this.rate = value;
    }

    /**
     * Gets the value of the rateAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getRateAdjustment() {
        return rateAdjustment;
    }

    /**
     * Sets the value of the rateAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setRateAdjustment(Quantity value) {
        this.rateAdjustment = value;
    }

    /**
     * Gets the value of the maxVolumeToDeliver property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getMaxVolumeToDeliver() {
        return maxVolumeToDeliver;
    }

    /**
     * Sets the value of the maxVolumeToDeliver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setMaxVolumeToDeliver(Quantity value) {
        this.maxVolumeToDeliver = value;
    }

}
