//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Variation and Sequence data.
 * 
 * <p>Java class for Sequence.Repository complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sequence.Repository">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://hl7.org/fhir}uri" minOccurs="0"/>
 *         &lt;element name="name" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="structure" type="{http://hl7.org/fhir}uri" minOccurs="0"/>
 *         &lt;element name="variantId" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="readGroupSetId" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sequence.Repository", propOrder = {
    "url",
    "name",
    "structure",
    "variantId",
    "readGroupSetId"
})
@javax.xml.bind.annotation.XmlRootElement(name="SequenceRepository") 
public class SequenceRepository
    extends BackboneElement
{

    protected Uri url;
    protected String name;
    protected Uri structure;
    protected String variantId;
    protected String readGroupSetId;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link Uri }
     *     
     */
    public Uri getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uri }
     *     
     */
    public void setUrl(Uri value) {
        this.url = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link Uri }
     *     
     */
    public Uri getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uri }
     *     
     */
    public void setStructure(Uri value) {
        this.structure = value;
    }

    /**
     * Gets the value of the variantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantId() {
        return variantId;
    }

    /**
     * Sets the value of the variantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantId(String value) {
        this.variantId = value;
    }

    /**
     * Gets the value of the readGroupSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadGroupSetId() {
        return readGroupSetId;
    }

    /**
     * Sets the value of the readGroupSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadGroupSetId(String value) {
        this.readGroupSetId = value;
    }

}
