//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This resource defines a decision support rule of the form [on Event] if Condition then Action.
 * 
 * <p>Java class for DecisionSupportRule.Trigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionSupportRule.Trigger">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://hl7.org/fhir}DecisionSupportRuleTriggerType"/>
 *         &lt;element name="eventName" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="eventTimingTiming" type="{http://hl7.org/fhir}Timing"/>
 *           &lt;element name="eventTimingReference" type="{http://hl7.org/fhir}Reference"/>
 *           &lt;element name="eventTimingDate" type="{http://hl7.org/fhir}date"/>
 *           &lt;element name="eventTimingDateTime" type="{http://hl7.org/fhir}dateTime"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionSupportRule.Trigger", propOrder = {
    "type",
    "eventName",
    "eventTimingTiming",
    "eventTimingReference",
    "eventTimingDate",
    "eventTimingDateTime"
})
@javax.xml.bind.annotation.XmlRootElement(name="DecisionSupportRuleTrigger") 
public class DecisionSupportRuleTrigger
    extends BackboneElement
{

    @XmlElement(required = true)
    protected DecisionSupportRuleTriggerType type;
    protected String eventName;
    protected Timing eventTimingTiming;
    protected Reference eventTimingReference;
    protected Date eventTimingDate;
    protected DateTime eventTimingDateTime;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionSupportRuleTriggerType }
     *     
     */
    public DecisionSupportRuleTriggerType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionSupportRuleTriggerType }
     *     
     */
    public void setType(DecisionSupportRuleTriggerType value) {
        this.type = value;
    }

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the eventTimingTiming property.
     * 
     * @return
     *     possible object is
     *     {@link Timing }
     *     
     */
    public Timing getEventTimingTiming() {
        return eventTimingTiming;
    }

    /**
     * Sets the value of the eventTimingTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timing }
     *     
     */
    public void setEventTimingTiming(Timing value) {
        this.eventTimingTiming = value;
    }

    /**
     * Gets the value of the eventTimingReference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getEventTimingReference() {
        return eventTimingReference;
    }

    /**
     * Sets the value of the eventTimingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setEventTimingReference(Reference value) {
        this.eventTimingReference = value;
    }

    /**
     * Gets the value of the eventTimingDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getEventTimingDate() {
        return eventTimingDate;
    }

    /**
     * Sets the value of the eventTimingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setEventTimingDate(Date value) {
        this.eventTimingDate = value;
    }

    /**
     * Gets the value of the eventTimingDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getEventTimingDateTime() {
        return eventTimingDateTime;
    }

    /**
     * Sets the value of the eventTimingDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setEventTimingDateTime(DateTime value) {
        this.eventTimingDateTime = value;
    }

}
