//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This resource provides eligibility and plan details from the processing of an Eligibility resource.
 * 
 * <p>Java class for EligibilityResponse.BenefitBalance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EligibilityResponse.BenefitBalance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="category" type="{http://hl7.org/fhir}Coding"/>
 *         &lt;element name="subCategory" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="network" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="unit" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="term" type="{http://hl7.org/fhir}Coding" minOccurs="0"/>
 *         &lt;element name="financial" type="{http://hl7.org/fhir}EligibilityResponse.Financial" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EligibilityResponse.BenefitBalance", propOrder = {
    "category",
    "subCategory",
    "network",
    "unit",
    "term",
    "financial"
})
@javax.xml.bind.annotation.XmlRootElement(name="EligibilityResponseBenefitBalance") 
public class EligibilityResponseBenefitBalance
    extends BackboneElement
{

    @XmlElement(required = true)
    protected Coding category;
    protected Coding subCategory;
    protected Coding network;
    protected Coding unit;
    protected Coding term;
    protected List<EligibilityResponseFinancial> financial;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setCategory(Coding value) {
        this.category = value;
    }

    /**
     * Gets the value of the subCategory property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getSubCategory() {
        return subCategory;
    }

    /**
     * Sets the value of the subCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setSubCategory(Coding value) {
        this.subCategory = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setNetwork(Coding value) {
        this.network = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setUnit(Coding value) {
        this.unit = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setTerm(Coding value) {
        this.term = value;
    }

    /**
     * Gets the value of the financial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the financial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinancial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EligibilityResponseFinancial }
     * 
     * 
     */
    public List<EligibilityResponseFinancial> getFinancial() {
        if (financial == null) {
            financial = new ArrayList<EligibilityResponseFinancial>();
        }
        return this.financial;
    }

}
