//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sequenceType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sequenceType-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AA"/>
 *     &lt;enumeration value="DNA"/>
 *     &lt;enumeration value="RNA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sequenceType-list")
@XmlEnum
public enum SequenceTypeList {


    /**
     * Amino acid sequence
     * 
     */
    AA,

    /**
     * DNA Sequence
     * 
     */
    DNA,

    /**
     * RNA Sequence
     * 
     */
    RNA;

    public java.lang.String value() {
        return name();
    }

    public static SequenceTypeList fromValue(java.lang.String v) {
        return valueOf(v);
    }

}
