//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 02:43:29 AM EST 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModuleMetadataFocusType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModuleMetadataFocusType-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="patient-gender"/>
 *     &lt;enumeration value="patient-age-group"/>
 *     &lt;enumeration value="clinical-focus"/>
 *     &lt;enumeration value="target-user"/>
 *     &lt;enumeration value="workflow-setting"/>
 *     &lt;enumeration value="workflow-task"/>
 *     &lt;enumeration value="clinical-venue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ModuleMetadataFocusType-list")
@XmlEnum
public enum ModuleMetadataFocusTypeList {


    /**
     * The gender of the patient. For this item type, use HL7 administrative gender codes (OID: 2.16.840.1.113883.1.11.1)
     * 
     */
    @XmlEnumValue("patient-gender")
    PATIENT_GENDER("patient-gender"),

    /**
     * A patient demographic category for which this artifact is applicable. Allows specification of age groups using coded values originating from the MeSH Code system (OID: 2.16.840.1.113883.6.177). More specifically, only codes from the AgeGroupObservationValue value set are valid for this field  [2.16.840.1.113883.11.75]
     * 
     */
    @XmlEnumValue("patient-age-group")
    PATIENT_AGE_GROUP("patient-age-group"),

    /**
     * The clinical concept(s) addressed by the artifact.  For example, disease, diagnostic test interpretation, medication ordering. Please refer to the implementation guide on which code system and codes to use
     * 
     */
    @XmlEnumValue("clinical-focus")
    CLINICAL_FOCUS("clinical-focus"),

    /**
     * The user types to which an artifact is targeted.  For example, PCP, Patient, Cardiologist, Behavioral Professional, Oral Health Professional, Prescriber, etc... taken from the NUCC Health Care provider taxonomyCode system (OID: 2.16.840.1.113883.6.101)
     * 
     */
    @XmlEnumValue("target-user")
    TARGET_USER("target-user"),

    /**
     * The settings in which the artifact is intended for use.  For example, admission, pre-op, etc
     * 
     */
    @XmlEnumValue("workflow-setting")
    WORKFLOW_SETTING("workflow-setting"),

    /**
     * The context for the clinical task(s) represented by this artifact. Can be any task context represented by the HL7 ActTaskCode value set (OID: 2.16.840.1.113883.1.11.19846). General categories include: order entry, patient documentation and patient information review
     * 
     */
    @XmlEnumValue("workflow-task")
    WORKFLOW_TASK("workflow-task"),

    /**
     * The venue in which an artifact could be used.  For example, Outpatient, Inpatient, Home, Nursing home. The code value may originate from either the HL7 ActEncounter (OID: 2.16.840.1.113883.1.11.13955) or NUCC non-individual provider codes OID: 2.16.840.1.113883.1.11.19465
     * 
     */
    @XmlEnumValue("clinical-venue")
    CLINICAL_VENUE("clinical-venue");
    private final java.lang.String value;

    ModuleMetadataFocusTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ModuleMetadataFocusTypeList fromValue(java.lang.String v) {
        for (ModuleMetadataFocusTypeList c: ModuleMetadataFocusTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
