//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 01:13:51 PM EDT 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The base element used for all FHIR elements and resources - allows for them to be extended with extensions
 * 
 * <p>Java class for Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extension" type="{http://hl7.org/fhir}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://hl7.org/fhir}id-primitive" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element", propOrder = {
    "extension"
})
@XmlSeeAlso({
    InstanceAvailability.class,
    EncounterClass.class,
    HierarchicalRelationshipType.class,
    MedicationKind.class,
    BindingConformance.class,
    CarePlanActivityStatus.class,
    LocationStatus.class,
    CausalityExpectation.class,
    QueryOutcome.class,
    ExtensionContext.class,
    RestfulConformanceMode.class,
    DocumentMode.class,
    Attachment.class,
    ProvenanceEntityRole.class,
    SecurityEventAction.class,
    ResponseType.class,
    CompositionStatus.class,
    Decimal.class,
    DocumentReferenceStatus.class,
    CodeableConcept.class,
    NarrativeStatus.class,
    SupplyStatus.class,
    SensitivityStatus.class,
    ResourceReference.class,
    SecurityEventParticipantNetworkType.class,
    ConditionRelationshipType.class,
    UnitsOfTime.class,
    Schedule.class,
    ImagingModality.class,
    Address.class,
    AggregationMode.class,
    Id.class,
    GroupType.class,
    DateTime.class,
    ResourceProfileStatus.class,
    Instant.class,
    SupplyDispenseStatus.class,
    LocationMode.class,
    QuantityCompararator.class,
    OrderOutcomeStatus.class,
    DocumentRelationshipType.class,
    Uri.class,
    LinkType.class,
    EventTiming.class,
    Integer.class,
    Range.class,
    Base64Binary.class,
    IssueSeverity.class,
    SensitivityType.class,
    SampledDataDataType.class,
    Modality.class,
    SecurityEventObjectLifecycle.class,
    Code.class,
    PropertyRepresentation.class,
    CarePlanStatus.class,
    Oid.class,
    SecurityEventObjectType.class,
    RestfulOperationSystem.class,
    ReactionSeverity.class,
    SearchParamType.class,
    CompositionAttestationMode.class,
    MedicationAdministrationStatus.class,
    SampledData.class,
    MediaType.class,
    RestfulOperationType.class,
    EncounterState.class,
    FilterOperator.class,
    ObservationReliability.class,
    ConceptMapEquivalence.class,
    ConformanceStatementStatus.class,
    ContactUse.class,
    ObservationRelationshipType.class,
    IdentifierUse.class,
    QuestionnaireStatus.class,
    ExposureType.class,
    Identifier.class,
    AlertStatus.class,
    SecurityEventOutcome.class,
    org.hl7.fhir.String.class,
    MedicationPrescriptionStatus.class,
    Extension.class,
    SlicingRules.class,
    ContactSystem.class,
    ConditionStatus.class,
    NameUse.class,
    DiagnosticOrderStatus.class,
    SecurityEventObjectRole.class,
    MessageSignificanceCategory.class,
    Coding.class,
    Criticality.class,
    ScheduleRepeat.class,
    ObservationStatus.class,
    CarePlanActivityCategory.class,
    Ratio.class,
    DiagnosticReportStatus.class,
    Date.class,
    ValueSetStatus.class,
    ConstraintSeverity.class,
    ListMode.class,
    Uuid.class,
    CarePlanGoalStatus.class,
    Narrative.class,
    Period.class,
    ProcedureRelationshipType.class,
    HumanName.class,
    AddressUse.class,
    ConformanceEventMode.class,
    Quantity.class,
    Contact.class,
    BackboneElement.class,
    Boolean.class,
    MedicationDispenseStatus.class,
    DiagnosticOrderPriority.class
})
public class Element {

    protected List<Extension> extension;
    @XmlAttribute(name = "id")
    protected java.lang.String id;

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * 
     * 
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
